package co.edu.escuelaing.cvds.lab8.model;
import java.util.ArrayList;
public class Listas{

    public ArrayList<String> getNombres() {
        ArrayList<String> nombres = new ArrayList<String>();
        nombres.add("Juan");
        nombres.add("María");
        nombres.add("Pedro");
        nombres.add("Ana");
        nombres.add("Luis");
        nombres.add("Laura");
        nombres.add("Carlos");
        nombres.add("Sofía");
        nombres.add("Diego");
        nombres.add("Elena");
        nombres.add("Javier");
        nombres.add("Isabel");
        nombres.add("Miguel");
        nombres.add("Lucía");
        nombres.add("Andrés");
        nombres.add("Beatriz");
        nombres.add("Felipe");
        nombres.add("Carmen");
        nombres.add("Ricardo");
        nombres.add("Teresa");
        nombres.add("Fernando");
        nombres.add("Silvia");
        nombres.add("Antonio");
        nombres.add("Raquel");
        nombres.add("José");
        nombres.add("Paula");
        nombres.add("Manuel");
        nombres.add("Lorena");
        nombres.add("Roberto");
        nombres.add("Patricia");
        nombres.add("David");
        nombres.add("Clara");
        nombres.add("Alberto");
        nombres.add("Marta");
        nombres.add("Gabriel");
        nombres.add("Leticia");
        nombres.add("Héctor");
        nombres.add("Victoria");
        nombres.add("Rubén");
        nombres.add("Alejandra");
        nombres.add("Jorge");
        nombres.add("Rosa");
        nombres.add("Federico");
        nombres.add("Esther");
        nombres.add("Joaquín");
        nombres.add("Natalia");
        nombres.add("Emilio");
        nombres.add("Inés");
        nombres.add("Luisa");
        nombres.add("Cecilia");
        nombres.add("Nicolás");
        nombres.add("Olga");
        nombres.add("Ángel");
        nombres.add("Cristina");
        nombres.add("Arturo");
        nombres.add("Pilar");
        nombres.add("Simón");
        nombres.add("Rocío");
        nombres.add("Roberto");
        nombres.add("Elisa");
        nombres.add("Julián");
        nombres.add("Lourdes");
        nombres.add("Adrián");
        nombres.add("Marina");
        nombres.add("Samuel");
        nombres.add("Mónica");
        nombres.add("Félix");
        nombres.add("Sara");
        nombres.add("Álvaro");
        nombres.add("Clara");
        nombres.add("Raul");
        nombres.add("Gloria");
        nombres.add("Lucas");
        nombres.add("Alicia");
        nombres.add("Alejandro");
        nombres.add("Nuria");
        nombres.add("Francisco");
        nombres.add("Angela");
        nombres.add("Víctor");
        nombres.add("Verónica");
        nombres.add("René");
        nombres.add("Luz");
        nombres.add("Pablo");
        nombres.add("Diana");
        nombres.add("Xavier");
        nombres.add("Patricia");
        nombres.add("Josué");
        nombres.add("Eva");
        nombres.add("Simón");
        nombres.add("Valeria");
        nombres.add("Óscar");
        nombres.add("Belen");
        nombres.add("Germán");
        nombres.add("Nerea");
        nombres.add("Ricardo");
        nombres.add("Lara");
        nombres.add("Eduardo");
        nombres.add("Irene");
        nombres.add("Esteban");
        nombres.add("Ruth");
        nombres.add("Fernando");
        return nombres;
    }

    public ArrayList<String> getApellidos() {
        ArrayList<String> apellidos = new ArrayList<String>();
        apellidos.add("García");
        apellidos.add("Martínez");
        apellidos.add("López");
        apellidos.add("Rodríguez");
        apellidos.add("Pérez");
        apellidos.add("González");
        apellidos.add("Fernández");
        apellidos.add("Ramírez");
        apellidos.add("Torres");
        apellidos.add("Sánchez");
        apellidos.add("Díaz");
        apellidos.add("Moreno");
        apellidos.add("Ruiz");
        apellidos.add("Navarro");
        apellidos.add("Cruz");
        apellidos.add("Ortega");
        apellidos.add("Jiménez");
        apellidos.add("Hernández");
        apellidos.add("Santos");
        apellidos.add("Castillo");
        apellidos.add("Vargas");
        apellidos.add("Molina");
        apellidos.add("Rojas");
        apellidos.add("Castro");
        apellidos.add("Méndez");
        apellidos.add("Delgado");
        apellidos.add("Vega");
        apellidos.add("Guerrero");
        apellidos.add("Flores");
        apellidos.add("Silva");
        apellidos.add("Aguilar");
        apellidos.add("Peralta");
        apellidos.add("Ríos");
        apellidos.add("Fuentes");
        apellidos.add("Campos");
        apellidos.add("Salazar");
        apellidos.add("Romero");
        apellidos.add("Lara");
        apellidos.add("Cabrera");
        apellidos.add("Maldonado");
        apellidos.add("Villanueva");
        apellidos.add("León");
        apellidos.add("Medina");
        apellidos.add("Solís");
        apellidos.add("Montes");
        apellidos.add("Zamora");
        apellidos.add("Soto");
        apellidos.add("Pacheco");
        apellidos.add("Valencia");
        apellidos.add("Núñez");
        apellidos.add("Guerra");
        apellidos.add("Cortés");
        apellidos.add("Orozco");
        apellidos.add("Rivas");
        apellidos.add("Quintero");
        apellidos.add("Miranda");
        apellidos.add("Escobar");
        apellidos.add("Ibarra");
        apellidos.add("Arroyo");
        apellidos.add("Serrano");
        apellidos.add("Esparza");
        apellidos.add("Chávez");
        apellidos.add("Tovar");
        apellidos.add("Uribe");
        apellidos.add("Montero");
        apellidos.add("Villalobos");
        apellidos.add("Reyes");
        apellidos.add("Calderón");
        apellidos.add("Zúñiga");
        apellidos.add("Morales");
        apellidos.add("Bustamante");
        apellidos.add("Del Río");
        apellidos.add("Aguirre");
        apellidos.add("Gallegos");
        apellidos.add("Franco");
        apellidos.add("Valenzuela");
        apellidos.add("Mendoza");
        apellidos.add("Mora");
        apellidos.add("Cuevas");
        apellidos.add("Herrera");
        apellidos.add("Ponce");
        apellidos.add("Del Valle");
        apellidos.add("Camacho");
        apellidos.add("Barrios");
        apellidos.add("Luna");
        apellidos.add("Olvera");
        apellidos.add("Aranda");
        apellidos.add("Bautista");
        apellidos.add("Salas");
        apellidos.add("Bermúdez");
        apellidos.add("Téllez");
        apellidos.add("Contreras");
        apellidos.add("Sandoval");
        apellidos.add("Castañeda");
        apellidos.add("Barajas");
        apellidos.add("Guzmán");
        apellidos.add("Laguna");
        apellidos.add("Zavala");
        apellidos.add("Palacios");
        apellidos.add("Cervantes");
        apellidos.add("Herrero");
        return apellidos;
    }

    public ArrayList<String> getEmpresas() {
        ArrayList<String> empresas = new ArrayList<String>();
        empresas.add("Empresa A");
        empresas.add("Empresa B");
        empresas.add("Empresa C");
        empresas.add("Empresa D");
        empresas.add("Empresa E");
        empresas.add("Empresa F");
        empresas.add("Empresa G");
        empresas.add("Empresa H");
        empresas.add("Empresa I");
        empresas.add("Empresa J");
        empresas.add("Empresa K");
        empresas.add("Empresa L");
        empresas.add("Empresa M");
        empresas.add("Empresa N");
        empresas.add("Empresa O");
        empresas.add("Empresa P");
        empresas.add("Empresa Q");
        empresas.add("Empresa R");
        empresas.add("Empresa S");
        empresas.add("Empresa T");
        empresas.add("Empresa U");
        empresas.add("Empresa V");
        empresas.add("Empresa W");
        empresas.add("Empresa X");
        empresas.add("Empresa Y");
        empresas.add("Empresa Z");
        empresas.add("Empresa 1");
        empresas.add("Empresa 2");
        empresas.add("Empresa 3");
        empresas.add("Empresa 4");
        empresas.add("Empresa 5");
        empresas.add("Empresa 6");
        empresas.add("Empresa 7");
        empresas.add("Empresa 8");
        empresas.add("Empresa 9");
        empresas.add("Empresa 10");
        empresas.add("Empresa 11");
        empresas.add("Empresa 12");
        empresas.add("Empresa 13");
        empresas.add("Empresa 14");
        empresas.add("Empresa 15");
        empresas.add("Empresa 16");
        empresas.add("Empresa 17");
        empresas.add("Empresa 18");
        empresas.add("Empresa 19");
        empresas.add("Empresa 20");
        empresas.add("Empresa 21");
        empresas.add("Empresa 22");
        empresas.add("Empresa 23");
        empresas.add("Empresa 24");
        empresas.add("Empresa 25");
        return empresas;
    }

    public  ArrayList<String> getNITs() {
        ArrayList<String> nits = new ArrayList<String>();
        nits.add("123456789");
        nits.add("987654321");
        nits.add("567890123");
        nits.add("321098765");
        nits.add("234567890");
        nits.add("876543210");
        nits.add("456789012");
        nits.add("654321098");
        nits.add("345678901");
        nits.add("543210987");
        nits.add("432109876");
        nits.add("789012345");
        nits.add("678901234");
        nits.add("210987654");
        nits.add("901234567");
        nits.add("109876543");
        nits.add("789012345");
        nits.add("987654321");
        nits.add("123456789");
        nits.add("456789012");
        nits.add("567890123");
        nits.add("876543210");
        nits.add("321098765");
        nits.add("234567890");
        nits.add("654321098");
        nits.add("345678901");
        nits.add("543210987");
        nits.add("432109876");
        nits.add("789012345");
        nits.add("678901234");
        nits.add("210987654");
        nits.add("901234567");
        nits.add("109876543");
        nits.add("789012345");
        nits.add("987654321");
        nits.add("123456789");
        nits.add("456789012");
        nits.add("567890123");
        nits.add("876543210");
        nits.add("321098765");
        nits.add("234567890");
        nits.add("654321098");
        nits.add("345678901");
        nits.add("543210987");
        nits.add("432109876");
        nits.add("432109877");
        nits.add("432109870");
        nits.add("321098005");
        nits.add("432109807");
        nits.add("340078901");
        nits.add("876500210");
        return nits;
    }


}
