name: Java Maven CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'  # Especifica la distribución, por ejemplo, 'adopt' o 'adopt-hotspot'

    - name: Build with Maven (Compile Only)
      run: mvn compile --file pom.xml

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'  # Especifica la distribución, por ejemplo, 'adopt' o 'adopt-hotspot'

    - name: Test with Maven (Verify)
      run: mvn verify --file pom.xml

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy (Placeholder)
      run: echo "En construcción..."
